# .github/workflow/build.yml
name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.1

      # Install dependencies
      - run: pnpm i

      # Build and output webpack stats to artifacts/webpack-stats.json
      - run: pnpm run build --if-present
        env:
          SERVER_GRAPHCMS_ENDPOINT: ${{ secrets.SERVER_GRAPHCMS_ENDPOINT }}
          NEXT_PUBLIC_CLIENT_GRAPHCMS_ENDPOINT: ${{ secrets.NEXT_PUBLIC_CLIENT_GRAPHCMS_ENDPOINT }}
          GRAPHCMS_TOKEN: ${{ secrets.GRAPHCMS_TOKEN }}
          SERVER_GITHUB_ENDPOINT: ${{ secrets.SERVER_GITHUB_ENDPOINT }}
          NEXT_PUBLIC_CLIENT_GITHUB_ENDPOINT: ${{ secrets.NEXT_PUBLIC_CLIENT_GITHUB_ENDPOINT }}
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
      - run: ls .next/ -a

      # Send webpack stats and build information to RelativeCI
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@v1.1.0
        with:
          webpackStatsFile: ./.next/stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}